name: "require-issue"
description: "Checks if commit message or title include existing issue"

inputs:
  host:
    description: 'Issue tracker hostname'
    required: true
  token:
    description: 'Issue tracker access token'
    required: true
  type:
    description: 'Issue tracker type'
    required: true
    default: jira
  includeMerges:
    description: 'Include merge commits when checking for issues'
    required: false
    default: 'true'

runs:
  using: 'node12'
  main: 'dist/index.js'
